# Generated by Django 3.2.9 on 2022-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palyer_id', models.CharField(max_length=255, unique=True)),
                ('profile_photo', models.ImageField(default='images/user_default_image.png', null=True, upload_to='images/')),
                ('team', models.CharField(default=None, max_length=255, null=True)),
                ('amount', models.PositiveBigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('manager', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('original_amount', models.PositiveBigIntegerField(default=None, null=True)),
                ('balance_amount', models.PositiveBigIntegerField(default=None, null=True)),
            ],
        ),
    ]
