# Generated by Django 3.2.9 on 2022-03-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='palyer_id',
            new_name='player_id',
        ),
    ]
