# Generated by Django 3.2.9 on 2022-03-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('team_manager', models.CharField(max_length=255)),
                ('team_owner', models.CharField(max_length=255)),
                ('amount', models.PositiveBigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
