# Generated by Django 3.2.9 on 2022-03-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220309_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='amount',
            new_name='balance_amount',
        ),
        migrations.AddField(
            model_name='team',
            name='original_amount',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
