# Generated by Django 3.2.9 on 2022-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_palyer_id_profile_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255, unique=True)),
                ('team', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveBigIntegerField(default=None)),
            ],
        ),
    ]
