# Generated by Django 3.2.9 on 2022-03-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220309_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='play',
            field=models.CharField(default='Boller', max_length=255),
        ),
    ]
