# Generated by Django 3.2.9 on 2022-03-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_manager',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_owner',
            new_name='owner',
        ),
    ]
